; Auto-generated. Do not edit!


(cl:in-package tshirtbot-msg)


;//! \htmlinclude TShirtSizeFeedback.msg.html

(cl:defclass <TShirtSizeFeedback> (roslisp-msg-protocol:ros-message)
  ((status
    :reader status
    :initarg :status
    :type cl:integer
    :initform 0))
)

(cl:defclass TShirtSizeFeedback (<TShirtSizeFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TShirtSizeFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TShirtSizeFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tshirtbot-msg:<TShirtSizeFeedback> is deprecated: use tshirtbot-msg:TShirtSizeFeedback instead.")))

(cl:ensure-generic-function 'status-val :lambda-list '(m))
(cl:defmethod status-val ((m <TShirtSizeFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tshirtbot-msg:status-val is deprecated.  Use tshirtbot-msg:status instead.")
  (status m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TShirtSizeFeedback>) ostream)
  "Serializes a message object of type '<TShirtSizeFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'status)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TShirtSizeFeedback>) istream)
  "Deserializes a message object of type '<TShirtSizeFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'status) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TShirtSizeFeedback>)))
  "Returns string type for a message object of type '<TShirtSizeFeedback>"
  "tshirtbot/TShirtSizeFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TShirtSizeFeedback)))
  "Returns string type for a message object of type 'TShirtSizeFeedback"
  "tshirtbot/TShirtSizeFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TShirtSizeFeedback>)))
  "Returns md5sum for a message object of type '<TShirtSizeFeedback>"
  "86791dcf1de997ec7de5a0de7e4dcfcc")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TShirtSizeFeedback)))
  "Returns md5sum for a message object of type 'TShirtSizeFeedback"
  "86791dcf1de997ec7de5a0de7e4dcfcc")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TShirtSizeFeedback>)))
  "Returns full string definition for message of type '<TShirtSizeFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback definition~%int32 status~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TShirtSizeFeedback)))
  "Returns full string definition for message of type 'TShirtSizeFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback definition~%int32 status~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TShirtSizeFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TShirtSizeFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'TShirtSizeFeedback
    (cl:cons ':status (status msg))
))
