; Auto-generated. Do not edit!


(cl:in-package tshirtbot-msg)


;//! \htmlinclude TShirtSizeActionGoal.msg.html

(cl:defclass <TShirtSizeActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type tshirtbot-msg:TShirtSizeGoal
    :initform (cl:make-instance 'tshirtbot-msg:TShirtSizeGoal)))
)

(cl:defclass TShirtSizeActionGoal (<TShirtSizeActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TShirtSizeActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TShirtSizeActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tshirtbot-msg:<TShirtSizeActionGoal> is deprecated: use tshirtbot-msg:TShirtSizeActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <TShirtSizeActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tshirtbot-msg:header-val is deprecated.  Use tshirtbot-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <TShirtSizeActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tshirtbot-msg:goal_id-val is deprecated.  Use tshirtbot-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <TShirtSizeActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tshirtbot-msg:goal-val is deprecated.  Use tshirtbot-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TShirtSizeActionGoal>) ostream)
  "Serializes a message object of type '<TShirtSizeActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TShirtSizeActionGoal>) istream)
  "Deserializes a message object of type '<TShirtSizeActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TShirtSizeActionGoal>)))
  "Returns string type for a message object of type '<TShirtSizeActionGoal>"
  "tshirtbot/TShirtSizeActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TShirtSizeActionGoal)))
  "Returns string type for a message object of type 'TShirtSizeActionGoal"
  "tshirtbot/TShirtSizeActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TShirtSizeActionGoal>)))
  "Returns md5sum for a message object of type '<TShirtSizeActionGoal>"
  "cdad59d9d127e253e43e305713ed334d")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TShirtSizeActionGoal)))
  "Returns md5sum for a message object of type 'TShirtSizeActionGoal"
  "cdad59d9d127e253e43e305713ed334d")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TShirtSizeActionGoal>)))
  "Returns full string definition for message of type '<TShirtSizeActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%TShirtSizeGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: tshirtbot/TShirtSizeGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%int32 size~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TShirtSizeActionGoal)))
  "Returns full string definition for message of type 'TShirtSizeActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%TShirtSizeGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: tshirtbot/TShirtSizeGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%int32 size~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TShirtSizeActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TShirtSizeActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'TShirtSizeActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
