// Generated by gencpp from file tshirtbot/TShirtSizeResult.msg
// DO NOT EDIT!


#ifndef TSHIRTBOT_MESSAGE_TSHIRTSIZERESULT_H
#define TSHIRTBOT_MESSAGE_TSHIRTSIZERESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tshirtbot
{
template <class ContainerAllocator>
struct TShirtSizeResult_
{
  typedef TShirtSizeResult_<ContainerAllocator> Type;

  TShirtSizeResult_()
    : code(0)  {
    }
  TShirtSizeResult_(const ContainerAllocator& _alloc)
    : code(0)  {
  (void)_alloc;
    }



   typedef int32_t _code_type;
  _code_type code;





  typedef boost::shared_ptr< ::tshirtbot::TShirtSizeResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tshirtbot::TShirtSizeResult_<ContainerAllocator> const> ConstPtr;

}; // struct TShirtSizeResult_

typedef ::tshirtbot::TShirtSizeResult_<std::allocator<void> > TShirtSizeResult;

typedef boost::shared_ptr< ::tshirtbot::TShirtSizeResult > TShirtSizeResultPtr;
typedef boost::shared_ptr< ::tshirtbot::TShirtSizeResult const> TShirtSizeResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tshirtbot::TShirtSizeResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tshirtbot::TShirtSizeResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace tshirtbot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'tshirtbot': ['/home/nickp/Desktop/aws-robomaker-sample-application-roverrobotics/build/tshirtbot/devel/share/tshirtbot/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::tshirtbot::TShirtSizeResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tshirtbot::TShirtSizeResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tshirtbot::TShirtSizeResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tshirtbot::TShirtSizeResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tshirtbot::TShirtSizeResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tshirtbot::TShirtSizeResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tshirtbot::TShirtSizeResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5e8de1acec506dc927ef4d2e8193b594";
  }

  static const char* value(const ::tshirtbot::TShirtSizeResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5e8de1acec506dc9ULL;
  static const uint64_t static_value2 = 0x27ef4d2e8193b594ULL;
};

template<class ContainerAllocator>
struct DataType< ::tshirtbot::TShirtSizeResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tshirtbot/TShirtSizeResult";
  }

  static const char* value(const ::tshirtbot::TShirtSizeResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tshirtbot::TShirtSizeResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
int32 code\n\
";
  }

  static const char* value(const ::tshirtbot::TShirtSizeResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tshirtbot::TShirtSizeResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TShirtSizeResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tshirtbot::TShirtSizeResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tshirtbot::TShirtSizeResult_<ContainerAllocator>& v)
  {
    s << indent << "code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TSHIRTBOT_MESSAGE_TSHIRTSIZERESULT_H
