(cl:defpackage rr_openrover_basic-msg
  (:use )
  (:export
   "<RAWRROPENROVERBASICFASTRATEDATA>"
   "RAWRROPENROVERBASICFASTRATEDATA"
   "<RAWRROPENROVERBASICMEDRATEDATA>"
   "RAWRROPENROVERBASICMEDRATEDATA"
   "<RAWRROPENROVERBASICSLOWRATEDATA>"
   "RAWRROPENROVERBASICSLOWRATEDATA"
   "<SMARTBATTERYSTATUS>"
   "SMARTBATTERYSTATUS"
  ))

