(cl:defpackage tshirt_dispense_msgs-msg
  (:use )
  (:export
   "<TSHIRTDISPENSEACTION>"
   "TSHIRTDISPENSEACTION"
   "<TSHIRTDISPENSEACTIONFEEDBACK>"
   "TSHIRTDISPENSEACTIONFEEDBACK"
   "<TSHIRTDISPENSEACTIONGOAL>"
   "TSHIRTDISPENSEACTIONGOAL"
   "<TSHIRTDISPENSEACTIONRESULT>"
   "TSHIRTDISPENSEACTIONRESULT"
   "<TSHIRTDISPENSEFEEDBACK>"
   "TSHIRTDISPENSEFEEDBACK"
   "<TSHIRTDISPENSEGOAL>"
   "TSHIRTDISPENSEGOAL"
   "<TSHIRTDISPENSERESULT>"
   "TSHIRTDISPENSERESULT"
  ))

