; Auto-generated. Do not edit!


(cl:in-package tshirtbot-msg)


;//! \htmlinclude TShirtSizeResult.msg.html

(cl:defclass <TShirtSizeResult> (roslisp-msg-protocol:ros-message)
  ((code
    :reader code
    :initarg :code
    :type cl:integer
    :initform 0))
)

(cl:defclass TShirtSizeResult (<TShirtSizeResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TShirtSizeResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TShirtSizeResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tshirtbot-msg:<TShirtSizeResult> is deprecated: use tshirtbot-msg:TShirtSizeResult instead.")))

(cl:ensure-generic-function 'code-val :lambda-list '(m))
(cl:defmethod code-val ((m <TShirtSizeResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tshirtbot-msg:code-val is deprecated.  Use tshirtbot-msg:code instead.")
  (code m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TShirtSizeResult>) ostream)
  "Serializes a message object of type '<TShirtSizeResult>"
  (cl:let* ((signed (cl:slot-value msg 'code)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TShirtSizeResult>) istream)
  "Deserializes a message object of type '<TShirtSizeResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'code) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TShirtSizeResult>)))
  "Returns string type for a message object of type '<TShirtSizeResult>"
  "tshirtbot/TShirtSizeResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TShirtSizeResult)))
  "Returns string type for a message object of type 'TShirtSizeResult"
  "tshirtbot/TShirtSizeResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TShirtSizeResult>)))
  "Returns md5sum for a message object of type '<TShirtSizeResult>"
  "5e8de1acec506dc927ef4d2e8193b594")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TShirtSizeResult)))
  "Returns md5sum for a message object of type 'TShirtSizeResult"
  "5e8de1acec506dc927ef4d2e8193b594")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TShirtSizeResult>)))
  "Returns full string definition for message of type '<TShirtSizeResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%int32 code~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TShirtSizeResult)))
  "Returns full string definition for message of type 'TShirtSizeResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%int32 code~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TShirtSizeResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TShirtSizeResult>))
  "Converts a ROS message object to a list"
  (cl:list 'TShirtSizeResult
    (cl:cons ':code (code msg))
))
