; Auto-generated. Do not edit!


(cl:in-package tshirt_dispense_msgs-msg)


;//! \htmlinclude TShirtDispenseResult.msg.html

(cl:defclass <TShirtDispenseResult> (roslisp-msg-protocol:ros-message)
  ((code
    :reader code
    :initarg :code
    :type cl:integer
    :initform 0))
)

(cl:defclass TShirtDispenseResult (<TShirtDispenseResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <TShirtDispenseResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'TShirtDispenseResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name tshirt_dispense_msgs-msg:<TShirtDispenseResult> is deprecated: use tshirt_dispense_msgs-msg:TShirtDispenseResult instead.")))

(cl:ensure-generic-function 'code-val :lambda-list '(m))
(cl:defmethod code-val ((m <TShirtDispenseResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader tshirt_dispense_msgs-msg:code-val is deprecated.  Use tshirt_dispense_msgs-msg:code instead.")
  (code m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <TShirtDispenseResult>) ostream)
  "Serializes a message object of type '<TShirtDispenseResult>"
  (cl:let* ((signed (cl:slot-value msg 'code)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <TShirtDispenseResult>) istream)
  "Deserializes a message object of type '<TShirtDispenseResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'code) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<TShirtDispenseResult>)))
  "Returns string type for a message object of type '<TShirtDispenseResult>"
  "tshirt_dispense_msgs/TShirtDispenseResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'TShirtDispenseResult)))
  "Returns string type for a message object of type 'TShirtDispenseResult"
  "tshirt_dispense_msgs/TShirtDispenseResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<TShirtDispenseResult>)))
  "Returns md5sum for a message object of type '<TShirtDispenseResult>"
  "5e8de1acec506dc927ef4d2e8193b594")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'TShirtDispenseResult)))
  "Returns md5sum for a message object of type 'TShirtDispenseResult"
  "5e8de1acec506dc927ef4d2e8193b594")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<TShirtDispenseResult>)))
  "Returns full string definition for message of type '<TShirtDispenseResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result defintion~%int32 code~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'TShirtDispenseResult)))
  "Returns full string definition for message of type 'TShirtDispenseResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result defintion~%int32 code~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <TShirtDispenseResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <TShirtDispenseResult>))
  "Converts a ROS message object to a list"
  (cl:list 'TShirtDispenseResult
    (cl:cons ':code (code msg))
))
